Don't append _wakeup_queue to queue list
Causes permission errors upon reconnecting to broker:

2010-05-23 18:57:57,718 mtrpc.server:ERROR @RPCManager: Attempt to reinitialize AMQP communication (after problem: error(4, 'Interrupted system call')) failed. Raising AMQPError...
2010-05-23 18:57:57,718 mtrpc.server:ERROR @RPCManager: Service thread activity broken with error: Traceback (most recent call last):
  File "/usr/local/megiteam/python2.6/mtrpc/server/threads.py", line 466, in amqp_init
    auto_delete=False)
  File "build/bdist.linux-x86_64/egg/amqplib/client_0_8/channel.py", line 1294, in queue_declare
    (50, 11),    # Channel.queue_declare_ok
  File "build/bdist.linux-x86_64/egg/amqplib/client_0_8/abstract_channel.py", line 105, in wait
    return amqp_method(self, args)
  File "build/bdist.linux-x86_64/egg/amqplib/client_0_8/channel.py", line 273, in _close
    (class_id, method_id))
AMQPChannelException: (403, u"ACCESS_REFUSED - access to queue '_wakeup_queue' in vhost '/' refused for user 'agent_vk1001'", (50, 10), 'Channel.queue_declare')